class HashTest < ActiveRecord::Migration
  def change
    add_column :q1
    add_column :q2
    add_column :q3
    add_column :q4  
    add_column :q5
    add_column :q6
    add_column :q7
    add_column :q8
    add_column :q9
    add_column :q10
    add_column :q11
    add_column :q12
    add_column :q13
    add_column :q14 
    add_column :q15
    add_column :psq1
    add_column :psq2
    add_column :psq3
    add_column :psq4
    add_column :psq5
    add_column :psq6
    add_column :psq7
    add_column :psq8
    add_column :psq9
    add_column :psq10
    add_column :psq11
    add_column :psq12
    add_column :psq13
    add_column :psq14
    add_column :psq15
    add_column :psq16
    add_column :psq17
    add_column :psq18
    add_column :psq19
    add_column :psq20
    add_column :psq21
    add_column :psq22
    add_column :psq23
    add_column :psq24
    add_column :psq25
    add_column :psq26
    add_column :psq27
    add_column :psq28
    add_column :psq29
    add_column :psq30
    add_column :psq31
    add_column :psq32
    add_column :psq32
    add_column :psq33
    add_column :psq34
    add_column :psq35
    add_column :psq36
    add_column :psq37
    add_column :psq38
    add_column :psq39
    add_column :special_response
  end
end
