class HashTest < ActiveRecord::Migration
  def change
    add_column :results :q1 :integer
    add_column :results :q2 :integer
    add_column :results :q3 :integer
    add_column :results :q4 :integer
    add_column :results :q5 :integer
    add_column :results :q6 :integer
    add_column :results :q7 :integer
    add_column :results :q8 :integer
    add_column :results :q9 :integer
    add_column :results :q10 :integer
    add_column :results :q11 :integer
    add_column :results :q12 :integer
    add_column :results :q13 :integer
    add_column :results :q14  :integer
    add_column :results :q15 :integer
    add_column :results :psq1 :integer
    add_column :results :psq2 :integer
    add_column :results :psq3 :integer
    add_column :results :psq4 :integer
    add_column :results :psq5 :integer
    add_column :results :psq6 :integer
    add_column :results :psq7 :integer
    add_column :results :psq8 :integer
    add_column :results :psq9 :integer
    add_column :results :psq10 :integer
    add_column :results :psq11 :integer
    add_column :results :psq12 :integer
    add_column :results :psq13 :integer
    add_column :results :psq14 :integer
    add_column :results :psq15 :integer
    add_column :results :psq16 :integer
    add_column :results :psq17 :integer
    add_column :results :psq18 :integer
    add_column :results :psq19 :integer
    add_column :results :psq20 :integer
    add_column :results :psq21 :integer
    add_column :results :psq22 :integer
    add_column :results :psq23 :integer
    add_column :results :psq24 :integer
    add_column :results :psq25 :integer
    add_column :results :psq26 :integer
    add_column :results :psq27 :integer
    add_column :results :psq28 :integer
    add_column :results :psq29 :integer
    add_column :results :psq30 :integer
    add_column :results :psq31 :integer
    add_column :results :psq32 :integer
    add_column :results :psq32 :integer
    add_column :results :psq33 :integer
    add_column :results :psq34 :integer
    add_column :results :psq35 :integer
    add_column :results :psq36 :integer
    add_column :results :psq37 :integer
    add_column :results :psq38 :integer
    add_column :results :psq39 :integer
  end
end
